#!/usr/bin/env python3
"""One-off: rename the brokerage entity site-wide.

Debbie now operates under her own brokerage — Debbie Cooley Mortgage,
company NMLS# 836635 — not Innovative Mortgage Services, Inc. (NMLS# 250769).

The build scripts (_build_pages.py, _build_phase3.py, _build_phase4.py) were
already corrected at source. This script patches the files NOT regenerated by
re-running the local builds: index.html, blog.html, the 30 blog posts,
resources/refinancing-during-divorce.html, and llms.txt.

Idempotent — files already correct are skipped.
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent

# Ordered longest-match-first so no replacement eats another's substring.
HTML_REPLACEMENTS = [
    # JSON-LD description + body bios: "Debbie Cooley Mortgage, a branch of …"
    (', a branch of Innovative Mortgage Services, Inc.', ''),
    # Garbled WP bio: "…Debbie Cooley Mortgage, a branch of Innovative Mortgage she has…"
    (', a branch of Innovative Mortgage she has', '. She has'),
    # Body CTA: "Call Debbie @ Innovative Mortgage DBA Debbie Cooley Mortgage."
    ('Innovative Mortgage DBA Debbie Cooley Mortgage', 'Debbie Cooley Mortgage'),
    # Body CTA: "call Debbie Cooley Guy with Innovative Mortgage for more…"
    ('Debbie Cooley Guy with Innovative Mortgage', 'Debbie Cooley Guy at Debbie Cooley Mortgage'),
    # Header utility bar
    ('NMLS# 210817 &middot; IMS NMLS# 250769', 'NMLS# 210817 &middot; Company NMLS# 836635'),
    # Footer compliance line
    ('<strong>Innovative Mortgage Services, Inc.</strong> | NMLS# 250769',
     '<strong>Debbie Cooley Mortgage</strong> | NMLS# 836635'),
]

# llms.txt has its own phrasing
LLMS_REPLACEMENTS = [
    ('Sponsored by Innovative Mortgage Services, Inc. (NMLS# 250769).',
     'Brokerage: Debbie Cooley Mortgage (NMLS# 836635).'),
]


def patch(path: Path, replacements) -> bool:
    text = path.read_text()
    original = text
    for old, new in replacements:
        text = text.replace(old, new)
    if text != original:
        path.write_text(text)
        return True
    return False


# Every HTML file in the site (root + blog/ + resources/ + tools/)
html_files = sorted(
    set(ROOT.glob('*.html'))
    | set(ROOT.glob('blog/*.html'))
    | set(ROOT.glob('resources/*.html'))
    | set(ROOT.glob('tools/*.html'))
)

changed = 0
for f in html_files:
    if patch(f, HTML_REPLACEMENTS):
        changed += 1
        print(f'  ✓ {f.relative_to(ROOT)}')

llms = ROOT / 'llms.txt'
if llms.exists() and patch(llms, LLMS_REPLACEMENTS):
    changed += 1
    print('  ✓ llms.txt')

print(f'\nDone. Patched {changed} files.')
